title: Cybersecurity_Portfolio
description: Greetings! My name is Rafael Santamar√≠a Ortega, and I am a Security engineer with a passion for automating solutions to tacke cybersecurity problems and tasks. This page contains the documentation and code of my projects. You can paruse it at your leisure!
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
