title: Cybersecurity_Portfolio
description: Greetings! My name is Rafael Santamar√≠a Ortega, I'm a Cyber Defense Analyst with 13+ industry certifications, 20+ projects and 3+ years of experience in reputation defense analysis.
google_analytics:
theme: jekyll-theme-hacker
